name: iOS Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (iOS Simulator)
        run: |
          xcodebuild \
            -project "AirHockey.xcodeproj" \
            -scheme "AirHockey iOS" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator" \
            build \
            CODE_SIGNING_ALLOWED=NO
